baseURL = 'https://innumerablerandomformations.com/'
languageCode = 'en-us'
title = 'Innumerable Random Formations'
theme = 'irf-theme'

[params]
  logo = 'irf.'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true