baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
copyright = '© 2023 ABC Widgets, Inc.'

[params]
  logo = 'mnhs.'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"