baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site with the irf. theme'
copyright = '2024 irf.'

[params]
  logo = 'mnhs.'
  mastodon = 'irf'
  shortTitle = 'myShortTitle'

[outputs]
  home = ['html', 'rss']
  section = ['html']
  taxonomy = ['html']
  term = ['html']

[services]
  [services.rss]
    limit = 30