name = 'irf-theme'
license = 'MIT'
licenselink = 'https://github.com/irfdot/irf/blob/main/LICENSE'
description = 'A minimal Hugo theme for personal essays'

homepage = 'https://github.com/irfdot/irf'
demosite = 'https://innumerablerandomformations.com'

# If the theme has a single author
[author]
  name = 'Umit Aslan'
  homepage = 'https://www.umitaslan.com'